name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - id: deployment
        uses: actions/deploy-pages@v4
  verify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Pages to be live
        run: |
          URL="https://damir224.github.io/TrafficManager/"
          echo "Checking $URL"
          for i in {1..10}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$URL");
            echo "Attempt $i: HTTP $code";
            if [ "$code" = "200" ]; then
              break;
            fi;
            sleep 15;
          done
          test "$code" = "200"
      - name: Headless verify with Playwright
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - name: Check HUD and canvas via Playwright
        env:
          BASE_URL: https://damir224.github.io/TrafficManager/
          SKIP_WEBSERVER: "1"
        run: npx playwright test -c playwright.config.cjs e2e/smoke.spec.js
